#!/bin/sh

# 1. Tastatur: Sofort laden (kein sleep nötig)
setxkbmap -layout us,de,ara -option grp:win_space_toggle &

# 2. Statusleiste: Startet im Hintergrund
slstatus &

# 3. Grafik & Wallpaper: 1 Sekunde warten für Stabilität
(sleep 1 && feh --bg-scale /usr/share/backgrounds/Fuwafuwa_nanbatto_san_by_amaral-dark.png) &
(sleep 1 && picom) &

# Falls du ein Tool für die Bildschirmhelligkeit nutzt, hier einfügen:
# xbacklight -set 50 &

# Schließlich dwm starten
exec dwm