#!/bin/sh

# Set the wallpaper (ensure path is correct)
feh --bg-scale /usr/share/backgrounds/Fuwafuwa_nanbatto_san_by_amaral-dark.png &

# Add other startup apps here

# Finally, execute dwm
exec dwm