#!/bin/sh

BG="#080b11"
FG="#a3b3d0"
SEL_BG="#1d2155"
SEL_FG="#dde3ed"
FONT="JetBrainsMono Nerd Font:size=10"

options="WIFI\nBLUETOOTH\nVPN\nPOWER"

chosen=$(echo -e "$options" | dmenu -c -l 10 -p "SYSTEM:" -fn "$FONT" -nb "$BG" -nf "$FG" -sb "$SEL_BG" -sf "$SEL_FG")

case "$chosen" in
    WIFI)
        gnome-terminal -- nmtui
        ;;
    BLUETOOTH)
        gnome-terminal -- bluetoothctl
        ;;
    VPN)
        vpn_choice=$(nmcli -g NAME,TYPE connection show | grep vpn | cut -d: -f1 | dmenu -c -l 5 -p "VPN-STEUERUNG:")
        if [ -n "$vpn_choice" ]; then
            if nmcli connection show --active | grep -q "$vpn_choice"; then
                nmcli connection down "$vpn_choice"
            else
                nmcli connection up "$vpn_choice"
            fi
        fi
        ;;
    POWER)
        pwr_choice=$(echo -e "REBOOT\nSHUTDOWN" | dmenu -c -l 5 -p "POWER:")
        [ "$pwr_choice" = "REBOOT" ] && reboot
        [ "$pwr_choice" = "SHUTDOWN" ] && poweroff
        ;;
esac